### ISSUE TITLE
'Look up' feature (tap with three fingers) is disabled

### ISSUE THREAD

**Issue by lamphanviet** [pilotmoon/Scroll-Reverser#17] opened 2015-03-07 00:13 UTC
The Look up (tap with three fingers) feature doesn't work when Scroll Reverser is running. I quit Scroll Reverser and it works again. There must be a bug here with Scroll Reverser.

**Comment by greengiraffe** [comment] 2015-03-13 13:11
I can confirm this issue on OS X 10.10.2

**Comment by invariant** [comment] 2015-05-21 11:45
Closed as dupe of #1.

Good news is I've found a fix  🎉😃

**Closed by invariant** 2015-05-21 11:45 UTC
