### ISSUE TITLE
Scroll Reverser jumps from backward and forward scrolling when using trackpad

### ISSUE THREAD

**Issue by ravenspired** [pilotmoon/Scroll-Reverser#131] opened 2021-11-17 16:10 UTC
Scroll Reverser jumps from backward and forward scrolling when using trackpad. This issue appeared after upgrading to macOS Monterey. It happens randomly for brief amounts of time. I only observed it when scrolling downward. Using M1 Macbook Pro (2020)
Thank you

**Comment by mrcsilva** [comment] 2021-11-18 09:15
Isn't this a duplicate of #129? I'm also seeing that problem and I think they already discussed that problem on that issue.

**Comment by invariant** [comment] 2021-11-18 13:26
Thanks for reporting @ravenspired, and thanks @mrcsilva - this is indeed a dupe of #129 so I will close this one

**Closed by invariant** 2021-11-18 13:26 UTC
