### ISSUE TITLE
Scroll not reversed in iPhone Mirroring App

### ISSUE THREAD

**Issue by linlang1837** [pilotmoon/Scroll-Reverser#190] opened 2024-09-18 09:03 UTC
In macOS Sequoia 15.0, users can now access and engage with their iPhone right from their Mac via "Mirror" App. But scroll is not reversed in the Mirror App.

**Comment by phpdave11** [comment] 2024-09-18 14:40
Duplicate of #184

**Comment by pilotmoon** [comment] 2024-11-17 10:23
Closed as duplicate

**Closed as completed by pilotmoon** 2024-11-17 10:23 UTC
