### ISSUE TITLE
Trackpad treated as mouse

### ISSUE THREAD

**Issue by wiiareonfire** [pilotmoon/Scroll-Reverser#23] opened 2015-09-19 16:14 UTC
Running the 10.11 El Capitan GM, and Scroll Reverser treats trackpad input as mouse input when selectively reversing scrolling behavior.

**Comment by invariant** [comment] 2015-10-05 15:51
Try quitting and restarting Scroll Reverser, it should reset to normal. I don't think this is a 10.11 issue but rather a general OS X issue which occurs on waking from sleep.

**Comment by andreasbroch** [comment] 2016-04-07 11:05
I get this problem when I have a bluetooth mouse connected and then disconnecting it as I will do every time I leave the house. When the mouse is connected the mouse and trackpad scrolls as expected. But when it is disconnected sudden the trackpad scrolls opposite.
Then I can restart scrollreverser as @invariant's said, but it is rather annoying to have to do it everytime the bluetooth mouse is disconnected.

**Comment by DarwinAwardWinner** [comment] 2016-06-02 02:24
I also have a similar problem. It seems to be triggered by some combination of suspend/resume and plugging/unplugging a USB mouse.

**Comment by levic** [comment] 2016-06-03 00:42
From issue #21:
> The way that Scroll Reverser identifies trackpad scrolling is to look for recent gesture events reporting 2 or more fingers on the pad. So if there are no gesture events then it can't sell whether it's a mouse or a trackpad.

I'm guessing that after resuming from sleep there are no gesture events and so it assumes it is a mouse

**Comment by DarwinAwardWinner** [comment] 2016-06-03 00:49
That's unfortunate that it has to rely on heuristics to identify a device. Is there really no official API to figure out the identity of a device?

**Comment by invariant** [comment] 2016-06-03 11:36
> That's unfortunate that it has to rely on heuristics to identify a device. Is there really no official API to figure out the identity of a device?

Not as far as I know, but if anyone does know, please tell me!

**Comment by invariant** [comment] 2016-06-03 11:39
So in general to address this issue in general - all these problems, as far as I can tell, are caused by problems in the input stream of events going to Scroll Reverser. Whether it's OS X bugs or what, I don't know. Anyway, the code is all here so if anyone has any good ideas for fixes, I'm very much open to pull requests.

**Comment by invariant** [comment] 2016-06-03 11:43
By the way you can ⌥-click the Scroll Reverser menu icon to bring up a debug window. This shows the event stream Scroll Reverser is seeing, and its interpretation of it.

![screen shot 2016-06-03 at 12 42 27](https://cloud.githubusercontent.com/assets/17520/15777611/a9646084-2988-11e6-89aa-c217ee01ec5d.png)

**Comment by invariant** [comment] 2016-11-07 15:15
Closing as (I think) dupe of #15

**Closed by invariant** 2016-11-07 15:15 UTC
Labels: bug
