### ISSUE TITLE
Trackpad identifying as mouse

### ISSUE THREAD

**Issue by natefox** [pilotmoon/Scroll-Reverser#21] opened 2015-06-05 23:10 UTC
I have a 2015 MBP and it appears my mouse and my trackpad are being seen as one in the same. Using the new debug console, I captured the following.
Note: 'notContinuous' = mouse  ; 'usingTouchElapsed' = trackpad

```
15:58:56.9 834 [type scroll][source mouse][reversing no][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 219175674][pid 0][x 0][y 1]
15:58:57.0 835 [type scroll][source mouse][reversing no][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 219175713][pid 0][x 0][y 1]
15:58:57.0 836 [type scroll][source mouse][reversing no][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 219175713][pid 0][x 0][y 1]
15:58:57.0 837 [type scroll][source mouse][reversing no][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 219175713][pid 0][x 0][y 1]
15:58:57.0 838 [type scroll][source mouse][reversing no][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 219175713][pid 0][x 0][y 0]
15:58:57.1 839 [type scroll][source mouse][reversing no][notContinuous yes][phase normal][touching 0][touchElapsed 219175867][pid 0][x 0][y -1]
15:58:57.3 840 [type scroll][source mouse][reversing no][notContinuous yes][phase normal][touching 0][touchElapsed 219176037][pid 0][x 0][y -1]
15:58:57.4 841 [type scroll][source mouse][reversing no][notContinuous yes][phase normal][touching 0][touchElapsed 219176159][pid 0][x 0][y -1]
15:58:57.5 842 [type scroll][source mouse][reversing no][notContinuous yes][phase normal][touching 0][touchElapsed 219176283][pid 0][x 0][y -2]
15:59:00.9 843 [type scroll][source mouse][reversing no][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 219179653][pid 0][x 0][y 0]
15:59:01.3 844 [type scroll][source mouse][reversing no][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 219180004][pid 0][x 0][y 0]
```

Is there something I can do to get them to be noticed as different devices? I'm using a Logitech M310 (part of the MK520 combo).

**Comment by invariant** [comment] 2015-06-08 09:14
It looks like Scroll Reverser is not seeing any gesture events in the stream. (These would appear as [type gesture] if they were present.) This suggests that the Logitech trackpad is not generating gesture events in the same way that the Apple trackpads do.

The way that Scroll Reverser identifies trackpad scrolling is to look for recent gesture events reporting 2 or more fingers on the pad. So if there are no gesture events then it can't sell whether it's a mouse or a trackpad.

That said there is something different which is the nonContinuous flag on your mouse. So in principle Scroll Reverser could reverse one and not the other however there is nothing built into the Scroll Reverser UI to set it to do that.

**Comment by invariant** [comment] 2016-09-22 14:49
Closing as dupe of #23 (although this issue is older, that one has more comments)

**Closed by invariant** 2016-09-22 14:49 UTC
