### ISSUE TITLE
Not starting at login

### ISSUE THREAD

**Issue by streetsoul00** [pilotmoon/Scroll-Reverser#174] opened 2024-01-26 14:20 UTC
Not starting at login. Checked and found that the app icon is also missing from the list Login Items.
Mac OS Sonoma 14.3
![image](https://github.com/pilotmoon/Scroll-Reverser/assets/157815063/e6218b9f-e771-41b4-9bfe-a63048f13888)
![image](https://github.com/pilotmoon/Scroll-Reverser/assets/157815063/6faec654-ab3f-4779-a51d-79e2a90b1452)

**Comment by pilotmoon** [comment] 2024-06-19 11:52
Closing as duplicate of #165. Should be fixed in the next build.

**Closed by pilotmoon** 2024-06-19 11:52 UTC
