### ISSUE TITLE
not support macOS Sierra

### ISSUE THREAD

**Issue by liman123** [pilotmoon/Scroll-Reverser#30] opened 2016-09-30 03:12 UTC
not support macOS Sierra , please fix it , thanks!

**Comment by invariant** [comment] 2016-09-30 08:11
It works on Sierra for me. Can you give any more detail as to whats going wrong? Error messages, crash, or just nor working?

**Comment by denbue** [comment] 2016-09-30 15:20
It does work on macOS Sierra, but I notice some strange behaviours of the touchpad that weren't there before. For example, in Adobe Programs (like Premiere Pro) the scrolling is stuttering while scroll reverser is open. When I close it, the touchpad performs normal again.

**Comment by wmwood** [comment] 2016-09-30 19:48
In macOS Sierra, the option for reverse mouse applies to both the trackpad and mouse. I prefer to reverse my mouse and leave my track pad as default. this behavior is broken.

**Comment by liman123** [comment] 2016-10-01 08:50
sorry, my mistake, it works on sierra, see my screenshot...
https://s9.postimg.org/l3u6kloov/Screen_Shot_2016_10_01_at_4_45_40_PM.png
https://s9.postimg.org/ckasmugcf/Screen_Shot_2016_10_01_at_4_45_32_PM.png

**Comment by Spin0za** [comment] 2016-10-04 16:09
@wmwood I have the same problem. @invariant @liman123 Could your scroll reverser on sierra set different direction on trackpad and mouse? I followed the setting in the screenshot but it doesn't work.

**Comment by bloemendal** [comment] 2016-10-05 07:02
I have the same issue as @wmwood. Seems like this #23 is happening, not sure if it's related since this is only the case on Sierra for me.

**Comment by bestwnh** [comment] 2016-10-06 03:03
same issue. The reverse mouse function effect the trackpad. 
But today I try to debug this issue, it's gone. I don't know how it happen, I just reopen the app and toggle some settings. So if you can try to reproduce the issue after reopen it and make some change, just let me know. I will help to fix the issue.

**Comment by Spin0za** [comment] 2016-10-06 14:09
Magically it worked again after reopening, just as @bestwnh said. Thank you!

**Comment by Spin0za** [comment] 2016-10-07 15:44
@invariant @bestwnh Still needs fixing. The issue reoccurred every time the Mac awaked. Needs reopening every time to work again.

**Comment by bestwnh** [comment] 2016-10-08 08:15
@Spin0za I just manual close my macbook then reopen it, but the function still work fine. Could you provide me the steps that reproduce the issue?

**Comment by jerry9032** [comment] 2016-10-09 04:01
I'm just to report more details to this issue, but the problem disappeared when I reopen it, as @bestwnh said. I don't know why... Apparently, it does reopen after system upgrading and rebooting.

Anyway, thank you @bestwnh !

**Comment by molisoft** [comment] 2016-10-11 02:16
+1

**Comment by Spin0za** [comment] 2016-10-11 13:33
@bestwnh To reproduce the issue, simply let the mac sleep and then wake it. I guess you were closing the lid and immediately reopening it, so it didn't sleep.

**Comment by Spin0za** [comment] 2016-10-14 13:39
@bestwnh It seems manually let the mac sleep and wake it immediately won't necessarily reproduce the issue. But what I'm sure of is that every morning when I wake my mac from a night's sleep, the issue will reappear.

**Comment by bloemendal** [comment] 2016-10-18 10:15
@bestwnh tried reopening and toggling stuff multiple times. The 'reverse trackpad' button doesn't seem to do anything since Sierra for me when reverse scrolling is enabled. 'Reverse mouse' works too well, because it not only reverses mouse but also reverses trackpad.

This is my log, first three are mouse down scrolls. From 3 on are touchpad down movements.
`12:14:09.3 Log started [on yes][v yes][h no][trackpad no][tablet no][mouse/other yes]
12:14:17.7 0 [type scroll][source mouse][reversing yes][notContinuous yes][phase normal][touching 0][touchElapsed 137896614][pid 0][x 0][y 1]
12:14:18.5 1 [type scroll][source mouse][reversing yes][notContinuous yes][phase normal][touching 0][touchElapsed 137897466][pid 0][x 0][y 1]
12:14:19.4 2 [type scroll][source mouse][reversing yes][notContinuous yes][phase normal][touching 0][touchElapsed 137898314][pid 0][x 0][y 1]
12:14:22.1 3 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 137901059][pid 0][x 0][y 0]
12:14:22.3 4 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 137901243][pid 0][x 0][y 1]
12:14:22.3 5 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 137901252][pid 0][x 0][y 1]
12:14:22.3 6 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 137901259][pid 0][x 0][y 1]
12:14:22.3 7 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 137901267][pid 0][x 0][y 1]
12:14:22.3 8 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 137901275][pid 0][x 0][y 1]
12:14:22.4 9 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 137901283][pid 0][x 0][y 1]
`

**Comment by invariant** [comment] 2016-10-18 11:09
Thanks for the log @bloemendal. The smoking gun is the line [touching 0]. This means that OS X is reporting to Scroll Reverser that there are no fingers on the trackpad. Is this an Apple trackpad?

**Comment by bestwnh** [comment] 2016-10-19 02:39
Thanks @bloemendal , I get this log before and just too busy in these days, but still a big thank you.
@invariant That log can produce by a trackpad in a Macbook Pro 2013 late. Not the apple wireless trackpad. I know a quick fix for this, but I don't know would that effect other situation and no time to figure out in these days.
In the `callback` method of `MouseTap.m`, insert a touching function and reset the `lastTouchTime` in
```
else if (type==NSScrollWheel) {
inset detect the touching code here, just like the code in "if (type==NSEventTypeGesture)"
...original code...
}
```
you would get the correct touching number with NSScrollWheel type in this situation.

Sorry for the delay and hope this can help you fix the issue.

**Comment by bestwnh** [comment] 2016-10-28 03:15
After upgrade to 10.12.1, it seems like the issue won't happen again. Can anyone help to confirm that?

**Comment by Spin0za** [comment] 2016-10-28 19:16
@bestwnh Nah... It's still happening on my mac with 10.12.1.

**Comment by bestwnh** [comment] 2016-10-30 14:17
I try to quick fix today but it won't work. It it works before. I don't know what happen. Sorry guys.
But I try another way to fix the issue. I builded a test version application. Hope you guys could help me to test it.
[Scroll Reverser.app.zip](https://github.com/pilotmoon/Scroll-Reverser/files/560529/Scroll.Reverser.app.zip)
Foe the test version, I added a relaunch button below menu "Preferences" to help fast relaunch the application. But more important thing is the application now would auto relaunch when the system awake from sleep(only effect macOS 10.12). So it should help to fix the issue.
PS: The application is unsigned, so you need to set the system's application security to "anywhere". And the update function is removed.
<img width="340" alt="screen shot 2016-10-30 at 22 07 40" src="https://cloud.githubusercontent.com/assets/1201345/19837082/4f627a6e-9eed-11e6-8801-6cde64779ff1.png">

Waiting for your feedback.

**Comment by kelvinkuo** [comment] 2016-11-01 07:12
@bestwnh the test version works well by now

**Comment by bestwnh** [comment] 2016-11-01 08:09
@kelvinkuo Good to know. Is anyone else test the test version with any feedback? I will create a PR later with enough feedback.

**Comment by invariant** [comment] 2016-11-01 13:08
Sounds good @bestwnh. I've been meaning to add something like this to auto relaunch upon waking from sleep. Feel free to create PR.

**Comment by invariant** [comment] 2016-11-07 14:05
I have now implemented a similar "relaunch on wake" feature in Scroll Reverser. I will release it later today. Closing this issue as dupe of #15.

**Closed by invariant** 2016-11-07 14:05 UTC
