### ISSUE TITLE
Scroll Reverse bounce bug in macOS 12.2

### ISSUE THREAD

**Issue by xszuflax** [pilotmoon/Scroll-Reverser#136] opened 2022-01-27 19:17 UTC
Hello,

after an update to macOS Monterey 12.2 Scroll Reverse is bouncing when scrolling with the Magic Mouse 2. I guess the video will show it best. I use reverse vertical scroll for a mouse. The touchpad is OK. 

Best,
Marcin

https://user-images.githubusercontent.com/10434553/151428232-0999672a-af65-4f63-8a32-e91941ecd908.mp4

**Comment by invariant** [comment] 2022-01-27 19:58
Confirmed, same for me.

**Comment by janhuntjens** [comment] 2022-01-27 21:38
Can confirm

**Comment by xszuflax** [comment] 2022-01-28 07:49
Hello, 

it looks like a Safari specific issue. I do not see this problem in Chrome and Electron Apps. Finder is OK, too.

Best,
MT

**Comment by craftey** [comment] 2022-01-30 21:52
After latest updates for Big Sur, the issue is now also present on macOS Big Sur.

macOS 11.6.2 (20G314)
Version 15.3 (16612.4.9.1.7, 16612)

**Comment by dummyVar** [comment] 2022-02-01 10:00
same issue

**Comment by spbgzh** [comment] 2022-02-04 16:42
it happened before
https://github.com/pilotmoon/Scroll-Reverser/issues/58

**Comment by xszuflax** [comment] 2022-02-04 16:56
Hello,

I believe it is a different thing. It does not affect the trackpad only a Magic Mouse 2 not even an external USB mouse with a wheel. It only happens in Safari 15.3 (17612.4.9.1.5). Scrolling in other apps is OK.

**Comment by xszuflax** [comment] 2022-02-05 08:16
If I was to blame something I would point fingers at scroll APIs for ProMotion. I don't have a mac that supports ProMotion thus I don't know other apps than Safari which supports 120 Hz screen refresh rates but I would be interesting to check if one could observe similar behavior

**Comment by dummyVar** [comment] 2022-02-05 10:44
I guess ProMotion isn't a point of problem. I had such issues on just a regular Mac and an hakintosh

**Comment by xszuflax** [comment] 2022-02-05 16:29
I do have this problem on my M1 MBP 13". What I'm trying to say is that maybe when Apple tried to implement better ProMotion they screwed the API for non ProMotion machines and now ScrollReverse is messed up.  I do not know any other ProMotion ready app to test my theory. The fact is that this is broken only in Safari and Apple was working in 12.2 on better ProMotion support.

**Comment by Cldfire** [comment] 2022-02-06 01:18
I'm experiencing the same bug on my ProMotion M1 Max MBP. Only happens in Safari. Versions:

* Safari 15.3 (17612.4.9.1.5)
* macOS 12.2 (21D49)

**Comment by thuzyc** [comment] 2022-02-08 03:55
I'm experiencing the same bug on my MacBook Pro (16-inch, 2019). Happens in Safari and DingTalk.

Versions:

- Safari 15.3 (17612.4.9.1.5)

- macOS 12.2 (21D49)

- DingTalk 6.3.25 (d456fd)

**Comment by moninfu** [comment] 2022-02-08 09:02
> Can confirm

Did you encounter any difficulties with bug fixes? Or is there any other alternative solution?

**Comment by invariant** [comment] 2022-02-08 09:34
> Did you encounter any difficulties with bug fixes? Or is there any other alternative solution?

Yes, great difficulty. I can't see any way to "fix" this in Scroll Reverser. As far as I can tell Scroll Reverser is continuing to do the correct thing, and Safari is interpreting the result weirdly, in a way I just don't understand. It's extremely frustrating. I'll write up in more detail if I can put it together in a way that makes sense.

**Comment by cfrederick95** [comment] 2022-02-08 20:30
Confirmed as well. Bug occurs with trackpad and mouse when reverse scroll is enabled. 

Safari Version 15.3 (17612.4.9.1.5)
Mac OS Monterey 12.2
M1 Max Macbook pro 16" with ProMotion

**Comment by moninfu** [comment] 2022-02-09 01:53
> > Did you encounter any difficulties with bug fixes? Or is there any other alternative solution?
> 
> Yes, great difficulty. I can't see any way to "fix" this in Scroll Reverser. As far as I can tell Scroll Reverser is continuing to do the correct thing, and Safari is interpreting the result weirdly, in a way I just don't understand. It's extremely frustrating. I'll write up in more detail if I can put it together in a way that makes sense.

I wish you the best of luck.
 I had to turn off the functionality of Scroll Reverser. 
In adapting to mouse rollback.  ：~（

**Comment by thuzyc** [comment] 2022-02-10 03:51
Another clue：Mac Quicklook is also affected..such as PDF preview with space bar.

**Comment by diazcal** [comment] 2022-02-10 08:20
It's such a weird issue. Everything works as expected when you scroll and don't let the macOS inertia to kick in. Once it begins to move by inertia the bounce effect appears.

To test it try to disable inertia in accessibility and try by yourself:

System Preferences > Accessibility > Pointer Control > Mouse (or Trackpad, whatever you use) Options > Scrolling without inertia. 

Hope it helps the developer debugging the issue 😄

**Comment by jtylerhartley** [comment] 2022-02-11 00:51
> 12.2.1 does not fix the issue :-/

Yes. It is the same for me unfortunately.

**Comment by diazcal** [comment] 2022-02-11 08:37
Some more info in case it is interesting for Nick or anybody else.

I tested Scroll Reverse against latest:
- Safari Technology Review: Release 140 (Safari 15.4, WebKit 16614.1.1.4)
- Safari Beta: Version 15.4 (16613.1.14.11.2, 16613)

Both have the same bouncing issue so whatever change they introduced in Safari/WebKit it's still there.

**Comment by CaptainZ1** [comment] 2022-02-12 23:34
This may just be adding to the pile, but FWIW even with "scrolling with inertia" enabled, scrolling slowly is a way to avoid the same 'rubber-banding' that is otherwise experienced. I also tried using UnnaturalScrollWheels, but it appears to be having similar issues, at least for me.... Here's hoping this is just a temporary Safari glitch that will be fixed in the next update! Thanks for looking into this!

**Comment by svnty** [comment] 2022-02-14 22:23
This has been happening to me for months

**Comment by cfrederick95** [comment] 2022-02-15 23:00
Update: The issue is not present on the start page for safari. Scroll reverser works as normal on this page. 
It seems like the issue only presents itself once you go to any other web page.

**Comment by cfrederick95** [comment] 2022-02-15 23:02
> 

The safari start page also seems to ignore whichever setting you have for scrolling with inertia. Turning it off will have no effect on the start page and inertia will still be present.

**Comment by lujjjh** [comment] 2022-02-17 08:14
Hey! I'm the author of [LinearMouse](https://github.com/linearmouse/linearmouse).

I'd like to share my approach to resolving this problem. That is, instead of modifying the event data in the event tap callback, [subscribe to the device events](https://github.com/linearmouse/linearmouse/blob/c6503bcb356e6299b75a4c4eac22f7ab90d2690e/LinearMouse/Device/DeviceManager.swift#L193-L212) and update the system-level scroll direction when the active device changes.

By using this approach, you can even configure different settings for different devices.

**Comment by svnty** [comment] 2022-02-17 08:20
> Hey! I'm the author of [LinearMouse](https://github.com/linearmouse/linearmouse).

hi, it didn't work for me, https://www.youtube.com/watch?v=GC1Jq6kkYWw

**Comment by lujjjh** [comment] 2022-02-17 08:29
> > Hey! I'm the author of [LinearMouse](https://github.com/linearmouse/linearmouse).
> 
> hi, it didn't work for me, https://www.youtube.com/watch?v=GC1Jq6kkYWw

Hi, @svnty!

Thank you very much for your video!

You may want to disable ‘Linear scrolling’ for Magic Mouse in the LinearMouse Preference.

Linear scrolling may have a similar issue that has yet to be resolved.

**Comment by dummyVar** [comment] 2022-02-17 08:43
> Hey! I'm the author of [LinearMouse](https://github.com/linearmouse/linearmouse).
> 
> I'd like to share my approach to resolving this problem. That is, instead of modifying the event data in the event tap callback, [subscribe to the device events](https://github.com/linearmouse/linearmouse/blob/c6503bcb356e6299b75a4c4eac22f7ab90d2690e/LinearMouse/Device/DeviceManager.swift#L193-L212) and update the system-level scroll direction when the active device changes.
> 
> By using this approach, you can even configure different settings for different devices.

Yep, for some period of time, I'm stick with yours product. Works almost perfect for now.

**Comment by lujjjh** [comment] 2022-02-17 16:30
I've found some magic bytes in the data of CGEvent. There is a signed int16 representing the delta (?). It seems that this issue could be resolved by simply modifying that number.

Here's a PoC written in Swift. You may save it as `main.swift` and run `swift main.swift`. Tested on macOS 12.2.1. Not sure if it works on earlier macOS versions.

```swift
#!/usr/bin/swift
import Foundation

let offset = 170

let eventTapCallback: CGEventTapCallBack = { (_, _, event, _) in
    let delta = event.getIntegerValueField(.scrollWheelEventDeltaAxis1)
    let fixedPtDelta = event.getDoubleValueField(.scrollWheelEventFixedPtDeltaAxis1)
    let pointDelta = event.getDoubleValueField(.scrollWheelEventPointDeltaAxis1)
    event.setIntegerValueField(.scrollWheelEventDeltaAxis1, value: -delta)
    event.setDoubleValueField(.scrollWheelEventFixedPtDeltaAxis1, value: -fixedPtDelta)
    event.setDoubleValueField(.scrollWheelEventPointDeltaAxis1, value: -pointDelta)
    var data = event.__data(allocator: kCFAllocatorDefault)! as Data
    let momentumPhase = event.getIntegerValueField(.scrollWheelEventMomentumPhase)
    if momentumPhase == CGMomentumScrollPhase.begin.rawValue {
        data.withUnsafeMutableBytes {
            let value = $0.load(fromByteOffset: offset, as: Int16.self)
            $0.storeBytes(of: -value, toByteOffset: offset, as: Int16.self)
        }
    }
    let event = CGEvent(withDataAllocator: kCFAllocatorDefault, data: data as CFData)!
    event.post(tap: .cgSessionEventTap)
    return nil
}

let eventsOfInterest: CGEventMask = 1 << CGEventType.scrollWheel.rawValue
let eventTap = CGEvent.tapCreate(
    tap: .cghidEventTap,
    place: .tailAppendEventTap,
    options: .defaultTap,
    eventsOfInterest: eventsOfInterest,
    callback: eventTapCallback,
    userInfo: nil
)
let runLoopSource = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, eventTap, 0)
CFRunLoopAddSource(CFRunLoopGetCurrent(), runLoopSource, CFRunLoopMode.commonModes)
CFRunLoopRun()
```

**Comment by diazcal** [comment] 2022-02-18 08:10
> Not only Safari, but Typora has the same problem.

Do you happen to know if Typora uses Webkit as part of their codebase?

**Comment by diazcal** [comment] 2022-02-18 08:52
Did a bit of research myself. Looks like Typora does use Webkit for the macOS version. Check the _Basic Rules_ chapter:
https://theme.typora.io/doc/Write-Custom-Theme/

The document is quite old so I hope that is still valid. If that's the case then indeed seems like a Webkit related issue.

**Comment by lujjjh** [comment] 2022-02-18 09:17
I looked at the WebKit source code and finally knew how WebKit recognizes the scroll direction.

It seems if we convert CGEvent to IOHIDEvent and fix its scrollY field, everything will work fine.

Tested on trackpad since I doesn't have a Magic Mouse.

```swift
import CoreGraphics
import Foundation

@objc protocol IOHIDEvent: NSObjectProtocol {}

let cgHandle = dlopen("/System/Library/Frameworks/CoreGraphics.framework/CoreGraphics", RTLD_NOW)
typealias CGEventCopyIOHIDEventType = @convention(c) (_ cgEvent: CGEvent) -> IOHIDEvent
let CGEventCopyIOHIDEvent = unsafeBitCast(dlsym(cgHandle, "CGEventCopyIOHIDEvent"), to: CGEventCopyIOHIDEventType.self)

let ioKitHandle = dlopen("/System/Library/Frameworks/IOKit.framework/IOKit", RTLD_NOW)
typealias IOHIDEventGetFloatValueType = @convention(c) (_ event: IOHIDEvent, UInt32) -> Double
let IOHIDEventGetFloatValue = unsafeBitCast(dlsym(ioKitHandle, "IOHIDEventGetFloatValue"), to: IOHIDEventGetFloatValueType.self)
typealias IOHIDEventSetFloatValueType = @convention(c) (_ event: IOHIDEvent, UInt32, Double) -> Void
let IOHIDEventSetFloatValue = unsafeBitCast(dlsym(ioKitHandle, "IOHIDEventSetFloatValue"), to: IOHIDEventSetFloatValueType.self)

let kIOHIDEventFieldScrollY: UInt32 = (6 << 16) | 1

let eventTapCallback: CGEventTapCallBack = { _, _, event, _ in
    // Reverse scrolling
    let delta = event.getIntegerValueField(.scrollWheelEventDeltaAxis1)
    let fixedPtDelta = event.getDoubleValueField(.scrollWheelEventFixedPtDeltaAxis1)
    let pointDelta = event.getDoubleValueField(.scrollWheelEventPointDeltaAxis1)
    event.setIntegerValueField(.scrollWheelEventDeltaAxis1, value: -delta)
    event.setDoubleValueField(.scrollWheelEventFixedPtDeltaAxis1, value: -fixedPtDelta)
    event.setDoubleValueField(.scrollWheelEventPointDeltaAxis1, value: -pointDelta)

    // Fix IOHIDEventFieldScrollY
    let momentumScrollPhase = CGMomentumScrollPhase(rawValue: UInt32(event.getIntegerValueField(.scrollWheelEventMomentumPhase)))!
    if momentumScrollPhase == .begin || momentumScrollPhase == .continuous {
        let iohidEvent = CGEventCopyIOHIDEvent(event)
        let scrollY = IOHIDEventGetFloatValue(iohidEvent, kIOHIDEventFieldScrollY)
        IOHIDEventSetFloatValue(iohidEvent, kIOHIDEventFieldScrollY, -scrollY)
    }

    return Unmanaged.passUnretained(event)
}

let eventsOfInterest: CGEventMask = 1 << CGEventType.scrollWheel.rawValue
let eventTap = CGEvent.tapCreate(
    tap: .cghidEventTap,
    place: .tailAppendEventTap,
    options: .defaultTap,
    eventsOfInterest: eventsOfInterest,
    callback: eventTapCallback,
    userInfo: nil
)
let runLoopSource = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, eventTap, 0)
CFRunLoopAddSource(CFRunLoopGetCurrent(), runLoopSource, CFRunLoopMode.commonModes)
CFRunLoopRun()
```

**Comment by lujjjh** [comment] 2022-02-18 10:44
I've submitted a pull request. It would be great if someone could test it with a Magic Mouse.

**Comment by dummyVar** [comment] 2022-02-18 10:56
> I've submitted a pull request. It would be great if someone could test it with a Magic Mouse.

it would be great to get compiled build with that fix

**Comment by craftey** [comment] 2022-02-18 15:10
> 

Using external Trackpad or internal Trackpad of Macbook Pro Retina 2015. Safari 15.3 on Big Sur.
The Build fixes the issue for me. Well done!🥳🥂Thank you!

**Comment by cfrederick95** [comment] 2022-02-18 16:53
Newest beta update fixed the issue for me as well! No issues across the board. 

Magic Mouse
Scroll Reverser Beta 10505
Safari Version 15.3 (17612.4.9.1.8)
Mac OS 12.2.1 (21D62)
M1 Max with ProMotion

**Comment by noahgaertner** [comment] 2022-02-19 18:06
Newest Beta update also fixed the issue for me on the trackpad for my 16" M1 Max on macOS 12.2.1

**Comment by Cldfire** [comment] 2022-02-20 03:57
> I'm experiencing the same bug on my ProMotion M1 Max MBP. Only happens in Safari. Versions:
> 
> * Safari 15.3 (17612.4.9.1.5)
> * macOS 12.2 (21D49)

The new beta release fixed everything for me. Thanks so much to those who worked to get to the bottom of this! 🙌

**Comment by invariant** [comment] 2022-03-09 16:45
Thanks for the feedback, everyone.  Since no problems were reported and it seem to work for everyone, I have now pushed out the update as v1.8.2 and I will close this issue.

**Closed by invariant** 2022-03-09 16:45 UTC
Labels: bug
